### ISSUE TITLE
Church should be an aux, not tied directly to main mix

### ISSUE THREAD

**Issue by rjmunro** [staldates/av-control#22]
* The church should not be handled differently to the other outputs - options like `all` and `main mix to all auxes` are currently confusing
* You should be able to use the main for the recording / other rooms, and leave the church on PC output, black, or even a logo from the ATEM memory. You could use fades / wipes etc. on the recording, and not affect the room

In general, most of the auxes should display main most of the time. Main would show up as an input that can be selected and sent to the outputs.

**Comment by jamesremuscat** [comment]
I disagree with several of your points - I'll try to find the time to properly write up why.

**Comment by jamesremuscat** [comment]
Having discussed this in person, and having taken some time to think about it further, I've almost managed to convince myself that this is a good thing after all.

I thought of an extra use case for it: displaying song words overlayed on a background on a projector on stage, while displaying words on a black background on the other screens. (Yes, we could do this with the M/E 2 bus, but not in a way straightforward to control from the touchscreen.) So, with two use-cases now identified, I started to think about implementation details.

I still disagree that `M/E 1 PGM ` should be an input button (although in some sense it already is, in the extras screen). I'm not sure it would make sense (or that the ATEM would allow!) to 'preview' it - `M/E 1 PRV` showing `M/E 1 PGM` gets confusing fast!

If, however, we take as axiomatic that "most of the auxes should display main most of the time" (completely agree - in particular leadership have been getting very confused if they can't see themselves on the stage screen, much as the band may like a direct PC feed), then we can build that assumption into the UI:

- Firstly, make sure the ATEM is configured to send `M/E 1 PGM` to all auxes on startup. (This should/might already be the case - it's certainly on my to-do list).
- Make it obvious when an aux output is _not_ displaying `M/E 1 PGM` - perhaps by giving the button a red background, perhaps by changing the font, etc.
- Long-press on an aux button to reset it to displaying `M/E 1 PGM`. Retain the "main to all auxes" button functionality, but relabel it as "mix to all" (or something similar).
  - I think it's important to keep this as a single, easily-accessible button to allow a quick "reset to sane parameters" for the aux outputs.
- Retain the "All" button and its existing functionality. (I'm not sure where the confusion you mentioned came from?)
- On the multiviewer screen, we could either:
  - Keep the large right-hand box as `M/E 1 PGM`, change the three output boxes to be `Church`, `Stage`, `Record` (e.g. lose `Gallery`); _or_
  - Change the large right-hand box to be `Church` (aux), switching `Gallery` for `M/E 1 PGM`?
I think I prefer the former.
- Ensure the nomenclature of labels on the multiviewer (and throughout the `av-control` UI) still makes accurate sense e.g. `Church / Main` => `Main mix` (or something similar).

We'll also need to repatch a number of inputs and outputs. I'd like to do this "properly" - moving things around on the patch bay where necessary, rather than just repatching - since having a clean default patch is appealing.

- At present the two distribution amplifiers are driven from two separate `M/E 1 PGM` outputs from the ATEM. We will need to instead drive them both from a single aux output - which means daisy-chaining the two together. We'll lose one DA output but we have several spare so that's acceptable to me. I'd like both of their inputs to be available on the patch bay, so move the input of DA 2 to the socket underneath the final output of DA 1.
- It might make sense to have the church output as aux 1, and shunt the others over by one (record 2, stage 3, gallery 4). This still leaves us two spare aux outputs (so we could potentially drive two projectors separately, etc).
- I'd like to retain the `M/E 1 PGM` outputs on the patch bay.

If/when all of that is agreed and  finalised, the tasks required will be:

- [ ] Configure ATEM to send `M/E 1 PGM` to all auxes on startup
- [ ] Design new [patch bay layout (only edit in actual MS Word - sizes and spacing critical!)](https://github.com/staldates/av-control/files/1314157/Patch.bay.labels.docx)
- [ ] Make UI changes to `av-control`
- [ ] Apply changes to patch bay
- [ ] Update ATEM `MVW 1` configuration and nomenclature
- [ ] Relabel patch bay
- [ ] Update user guide
- [ ] Deploy software changes

I think this could fit neatly into a update package for early January, in the post-Christmas lull. In the meantime, @rjmunro please would you be able to start drawing up a PR (or a redesigned patch bay layout)?

It is important to minimise end-user impact for these changes. Although there's quite a lot of change here, the end result won't be too different to how it is at present: the convention being established is "main to all auxes and run from there" and this won't impact that workflow.

I'm going to open this out for comment from visuals engineers, to see if there's anything I've missed or that doesn't make sense.

**Comment by jamesremuscat** [comment]
@rjmunro Have you made any progress with this so far? Want to make sure I don't accidentally duplicate effort!

**Comment by rjmunro** [comment]
No, sorry.

**Comment by jamesremuscat** [comment]
Required code changes now all merged to `develop`.

**Comment by jamesremuscat** [comment]
Thoughts on the patch bay: https://docs.google.com/spreadsheets/d/16IGX2EjXFd8T9THi7jOAG8zFg2SN3asF4kaXEntJU90

**Comment by jamesremuscat** [comment]
For reference here (had also been posted on the PR) - the slight changes to the UI look like this.

![av-control_019](https://user-images.githubusercontent.com/3471844/33713999-4ca66b2e-db45-11e7-91bf-c217b829bd77.png)

**Comment by jamesremuscat** [comment]
New patch bay labels:

https://drive.google.com/file/d/1D_WRoGIHuUq8wR9NzsaA0bilwo17U8A8/view?usp=sharing

**Comment by jamesremuscat** [comment]
The final task before we can close this is to update the user guide; that's in progress but there's a couple of screenshots I can't easily redo from home so they'll have to wait until I get into church next.

Everything else is done.

**Comment by jamesremuscat** [comment]
@rjmunro For some reason I can't save the switcher state to XML file (the ATEM software just gives me a document with an XML declaration and nothing else). When you're next in would you be able to do so (just after the switcher starts up) and check it in please?

**Comment by rjmunro** [comment]
Sure, I'll try to bring my laptop in and do it on Sunday.

**Comment by rjmunro** [comment]
This has been working well for a while now :-)
